CREATE DATABASE api_users;

USE api_users;

CREATE TABLE users(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    role TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);